// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWINcgCxa7AV6ocD_lvmDJ4JzjRvu5cDQ',
    appId: '1:210224111271:web:7c597fd3de3a7546674582',
    messagingSenderId: '210224111271',
    projectId: 'healttech-wl-staging',
    authDomain: 'healttech-wl-staging.firebaseapp.com',
    storageBucket: 'healttech-wl-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4yjQ_pLw-njk3Ud510wyjFsk86ASrPY0',
    appId: '1:210224111271:android:c754c4e8a1db85a3674582',
    messagingSenderId: '210224111271',
    projectId: 'healttech-wl-staging',
    storageBucket: 'healttech-wl-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCa0kWrLjHkFMIQQguHu7EF9xKRC-qlyk',
    appId: '1:210224111271:ios:c4a2e5d9851054d3674582',
    messagingSenderId: '210224111271',
    projectId: 'healttech-wl-staging',
    storageBucket: 'healttech-wl-staging.firebasestorage.app',
    iosBundleId: 'com.example.healthTechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCa0kWrLjHkFMIQQguHu7EF9xKRC-qlyk',
    appId: '1:210224111271:ios:c4a2e5d9851054d3674582',
    messagingSenderId: '210224111271',
    projectId: 'healttech-wl-staging',
    storageBucket: 'healttech-wl-staging.firebasestorage.app',
    iosBundleId: 'com.example.healthTechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWINcgCxa7AV6ocD_lvmDJ4JzjRvu5cDQ',
    appId: '1:210224111271:web:8d974d532df1ffe7674582',
    messagingSenderId: '210224111271',
    projectId: 'healttech-wl-staging',
    authDomain: 'healttech-wl-staging.firebaseapp.com',
    storageBucket: 'healttech-wl-staging.firebasestorage.app',
  );
}
